Fix back in time button and adds 2d meshes
rewin123/space_editor pull request #252
Opened 2024-03-11 00:43 UTC by naomijub

2024-03-12 19:58 UTC, rewin123 commented
I looked at the PR. Looks great, and I understand some of the scenes have been fixed, which is pretty cool too. I don't like the only change I noted in the review

2024-03-13 17:29 UTC, naomijub commented
> I looked at the PR. Looks great, and I understand some of the scenes have been fixed, which is pretty cool too. I don't like the only change I noted in the review

SOrry, I didn't get which note you left in the review. I dont see it

2024-03-13 18:56 UTC, rewin123 requested changes

2024-03-13 18:57 UTC, rewin123 commented
Oh, I didn't realise I had to hit the complete review button. Can you see it now?

2024-03-13 19:57 UTC, naomijub commented on crates/prefab/src/plugins.rs
> +        app.editor_relation::<Sprite, PrefabMarker>();
That makes sense, however, if we create a scene only using the bundle components, the saved scene would not work well. What can I do is determine if it is a root object, and if it is we add a prefab marker. 

So I can create a new sync function that removes prefab marker if the entity has parent

2024-03-13 21:14 UTC, merged